steps:
  # Step 1: Build Container Image using multi-stage Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ashky:latest', '.']

  # Step 2: Push Container Image to Google Container Registry / Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ashky:latest']

  # Step 3: Deploy to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ashky'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ashky:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--no-cpu-throttling'
      - '--cpu-boost'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '1'

images:
  - 'gcr.io/$PROJECT_ID/ashky:latest'
